from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    message: str = Field(..., description="The message from the frontend user")
    session_id: str | None = Field(
        default=None,
        description="Conversation session identifier used for memory persistence",
    )


class ChatResponse(BaseModel):
    reply: str = Field(..., description="The response generated by the AI")
    session_id: str = Field(..., description="Conversation session identifier")
    memory_messages_used: int = Field(
        ..., description="How many previous memory messages were included in prompt"
    )
    long_term_memory_used: bool = Field(
        ..., description="Whether long-term memory was included in prompt context"
    )
    semantic_memories_used: int = Field(
        ..., description="How many semantic memories were retrieved from Pinecone"
    )


class ChatMessageRead(BaseModel):
    role: str = Field(..., description="Message role: user or assistant")
    message: str = Field(..., description="Message content")


class ChatHistoryResponse(BaseModel):
    session_id: str = Field(..., description="Conversation session identifier")
    messages: list[ChatMessageRead] = Field(
        ..., description="Stored conversation memory messages"
    )


class ChatMemoryUpsertRequest(BaseModel):
    memory: str = Field(..., description="Long-term memory text to store for session")


class ChatMemoryReadResponse(BaseModel):
    session_id: str = Field(..., description="Conversation session identifier")
    memory: str = Field(..., description="Long-term memory content")


class ChatSemanticMemoryUpsertRequest(BaseModel):
    memory: str = Field(..., description="Semantic memory text to embed and store")


class ChatSemanticMemorySearchRequest(BaseModel):
    query: str = Field(..., description="Query used to search semantic memory")
    top_k: int = Field(default=3, ge=1, le=10, description="Number of results to return")


class ChatSemanticMemorySearchResponse(BaseModel):
    session_id: str = Field(..., description="Conversation session identifier")
    query: str = Field(..., description="Search query")
    memories: list[str] = Field(..., description="Retrieved semantic memory snippets")
