from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    message: str = Field(..., description="The message from the frontend user")

class ChatResponse(BaseModel):
    reply: str = Field(..., description="The response generated by the AI")
